image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test
  - release

build:
  stage: build
  script:
    - dotnet build

test:
  stage: test
  script:
    - dotnet test

release:
  stage: release
  only:
    - main
    - development
  artifacts:
    paths:
      - publish/
  script:
    - dotnet publish -c Release -o ../publish App/if3250_2022_19_filantropi_backend.csproj
