// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using if3250_2022_19_filantropi_backend.Data;

#nullable disable

namespace if3250_2022_19_filantropi_backend.Migrations
{
  [DbContext(typeof(DataContext))]
  partial class DataContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.2")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("if3250_2022_19_filantropi_backend.Models.User", b =>
          {
            b.Property<string>("Email")
                      .HasColumnType("text")
                      .HasColumnName("email");

            b.Property<int>("DonationAmount")
                      .HasColumnType("integer");

            b.Property<long>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("bigint")
                      .HasColumnName("id");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<string>("ImageUrl")
                      .HasColumnType("text");

            b.Property<string>("Name")
                      .HasColumnType("text");

            b.Property<string>("Password")
                      .IsRequired()
                      .HasColumnType("text");

            b.Property<string>("Role")
                      .IsRequired()
                      .HasColumnType("text");

            b.HasKey("Email");

            b.HasIndex("Email")
                      .IsUnique();

            b.ToTable("users", (string)null);
          });
#pragma warning restore 612, 618
    }
  }
}
